apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kargo-demo-project.yaml
- kargo-demo-repo-secret.yaml
- kargo-demo-warehouse.yaml
- kargo-demo-promotiontask.yaml
- kargo-demo-stage-prod.yaml
- kargo-demo-stage-test.yaml
- kargo-demo-stage-uat.yaml

sortOptions:
  order: fifo
