---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kargo-es
  namespace: kargo
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: kargo-demo-css
    kind: ClusterSecretStore
  target:
    name: kargo-admin-secret
  data:
  - secretKey: "ADMIN_ACCOUNT_PASSWORD_HASH"
    remoteRef:
      key: /data/kargo_admin_password_hash
      version: v1
  - secretKey: "ADMIN_ACCOUNT_TOKEN_SIGNING_KEY"
    remoteRef:
      key: /data/kargo_admin_token_signing_key
      version: v1
