apiVersion: kustomize.config.k8s.io/v1beta1

namespace: external-secrets

resources:
- external-secrets-ns.yaml

helmCharts:
- name: external-secrets
  version: 0.13.0
  repo: https://charts.external-secrets.io
  releaseName: external-secrets
  namespace: external-secrets
  valuesFile: values.yaml

