apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: kargo-config
  namespace: argocd
spec:
  project: config
  source:
    repoURL: https://github.com/bbigras/kargo-deployment-example
    targetRevision: main
    path: configs/kargo
  destination:
    #namespace: kargo
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    #syncOptions:
    #- CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
