apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: kargo
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://github.com/bbigras/kargo-deployment-example
    targetRevision: main
    path: system/kargo
  destination:
    namespace: kargo
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
