apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ingress-controller

resources: 
- ingress-controller-ns.yaml

helmCharts:
- name: ingress-nginx
  version: 4.12.0
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: nginx
  valuesFile: values.yaml

