---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-es
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: kargo-demo-css
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
  - secretKey: "admin.password"
    remoteRef:
      key: /data/admin_password
      version: v1
  - secretKey: "admin.passwordMtime"
    remoteRef:
      key: /data/admin_password_mtime
      version: v1
