apiVersion: kustomize.config.k8s.io/v1beta1

namespace: argocd

resources: 
- argocd-ns.yaml
- argocd-secret-eso.yaml

helmCharts:
- name: argo-cd
  version: 7.7.0
  repo: https://argoproj.github.io/argo-helm
  releaseName: argocd
  valuesFile: values.yaml

patches:
- target:
    version: v1
    kind: Secret
    name: argocd-initial-admin-secret
    namespace: argocd
  patch: |-
    $patch: delete
    apiVersion: v1
    kind: Secret
    metadata:
      name: argocd-initial-admin-secret
      namespace: argocd
