apiVersion: kustomize.config.k8s.io/v1beta1

namespace: argocd

resources: 
- argocd-ns.yaml

helmCharts:
- name: argo-cd
  version: 7.7.0
  repo: https://argoproj.github.io/argo-helm
  releaseName: argocd
  valuesFile: values.yaml
