#argo-cd:
configs:
  cm:
    kustomize.buildOptions: --enable-helm
    resource.customizations.health.networking.k8s.io_Ingress: "hs = {}\nhs.status = \"Healthy\"\nhs.message = \"Probably just fine\"\nreturn hs\n"
    resource.customizations.health.argoproj.io_Application: "hs = {}\nhs.status = \"Progressing\"\nhs.message = \"\"\nif obj.status ~= nil then\n  if obj.status.health ~= nil then\n    hs.status = obj.status.health.status\n    if obj.status.health.message ~= nil then\n      hs.message = obj.status.health.message\n    end\n  end\nend\nreturn hs\n"
dex:
  enabled: false
global:
  domain: argocd.7f000001.nip.io
notifications:
  enabled: false
server:
  extensions:
    contents:
    - name: argo-rollouts
      url: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.3/extension.tar
    enabled: true
  ingress:
    annotations:
      '"nginx.ingress.kubernetes.io/force-ssl-redirect"': true
      '"nginx.ingress.kubernetes.io/ssl-passthrough"': true
    enabled: true
    hostname: argocd.7f000001.nip.io
    ingressClassName: nginx
    tls: true
